# Generated by Django 2.0.2 on 2018-11-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydict',
            options={'ordering': ['id'], 'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='courseorg',
            options={'ordering': ['id'], 'verbose_name': '课程机构', 'verbose_name_plural': '课程机构'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id'], 'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
        migrations.AddField(
            model_name='courseorg',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
